/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PlayerIndexImport } from './routes/player/index'
import { Route as TeamIdImport } from './routes/team/$id'
import { Route as PlayerIdImport } from './routes/player/$id'
import { Route as GameIdImport } from './routes/game/$id'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const PlayerIndexRoute = PlayerIndexImport.update({
  id: '/player/',
  path: '/player/',
  getParentRoute: () => rootRoute,
} as any)

const TeamIdRoute = TeamIdImport.update({
  id: '/team/$id',
  path: '/team/$id',
  getParentRoute: () => rootRoute,
} as any)

const PlayerIdRoute = PlayerIdImport.update({
  id: '/player/$id',
  path: '/player/$id',
  getParentRoute: () => rootRoute,
} as any)

const GameIdRoute = GameIdImport.update({
  id: '/game/$id',
  path: '/game/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/game/$id': {
      id: '/game/$id'
      path: '/game/$id'
      fullPath: '/game/$id'
      preLoaderRoute: typeof GameIdImport
      parentRoute: typeof rootRoute
    }
    '/player/$id': {
      id: '/player/$id'
      path: '/player/$id'
      fullPath: '/player/$id'
      preLoaderRoute: typeof PlayerIdImport
      parentRoute: typeof rootRoute
    }
    '/team/$id': {
      id: '/team/$id'
      path: '/team/$id'
      fullPath: '/team/$id'
      preLoaderRoute: typeof TeamIdImport
      parentRoute: typeof rootRoute
    }
    '/player/': {
      id: '/player/'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof PlayerIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/game/$id': typeof GameIdRoute
  '/player/$id': typeof PlayerIdRoute
  '/team/$id': typeof TeamIdRoute
  '/player': typeof PlayerIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/game/$id': typeof GameIdRoute
  '/player/$id': typeof PlayerIdRoute
  '/team/$id': typeof TeamIdRoute
  '/player': typeof PlayerIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/game/$id': typeof GameIdRoute
  '/player/$id': typeof PlayerIdRoute
  '/team/$id': typeof TeamIdRoute
  '/player/': typeof PlayerIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/game/$id'
    | '/player/$id'
    | '/team/$id'
    | '/player'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/game/$id' | '/player/$id' | '/team/$id' | '/player'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/game/$id'
    | '/player/$id'
    | '/team/$id'
    | '/player/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AboutLazyRoute: typeof AboutLazyRoute
  GameIdRoute: typeof GameIdRoute
  PlayerIdRoute: typeof PlayerIdRoute
  TeamIdRoute: typeof TeamIdRoute
  PlayerIndexRoute: typeof PlayerIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutLazyRoute: AboutLazyRoute,
  GameIdRoute: GameIdRoute,
  PlayerIdRoute: PlayerIdRoute,
  TeamIdRoute: TeamIdRoute,
  PlayerIndexRoute: PlayerIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/game/$id",
        "/player/$id",
        "/team/$id",
        "/player/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/game/$id": {
      "filePath": "game/$id.tsx"
    },
    "/player/$id": {
      "filePath": "player/$id.tsx"
    },
    "/team/$id": {
      "filePath": "team/$id.tsx"
    },
    "/player/": {
      "filePath": "player/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
